# Generated by Django 3.2.6 on 2021-08-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=120, null=True, verbose_name='Title')),
                ('picture', models.ImageField(upload_to='media/departament/', verbose_name='Image')),
                ('one_list', models.CharField(max_length=120, verbose_name='One List')),
                ('one_list_ru', models.CharField(max_length=120, null=True, verbose_name='One List')),
                ('one_list_en', models.CharField(max_length=120, null=True, verbose_name='One List')),
                ('one_list_uz', models.CharField(max_length=120, null=True, verbose_name='One List')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('text1_ru', models.TextField(null=True, verbose_name='Text 1')),
                ('text1_en', models.TextField(null=True, verbose_name='Text 1')),
                ('text1_uz', models.TextField(null=True, verbose_name='Text 1')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('text2_ru', models.TextField(null=True, verbose_name='Text 2')),
                ('text2_en', models.TextField(null=True, verbose_name='Text 2')),
                ('text2_uz', models.TextField(null=True, verbose_name='Text 2')),
            ],
        ),
        migrations.CreateModel(
            name='FirstBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='First Block', max_length=20, verbose_name='First Block')),
                ('text_facultet1', models.CharField(max_length=120, verbose_name='Text facultet 1')),
                ('text_facultet1_ru', models.CharField(max_length=120, null=True, verbose_name='Text facultet 1')),
                ('text_facultet1_en', models.CharField(max_length=120, null=True, verbose_name='Text facultet 1')),
                ('text_facultet1_uz', models.CharField(max_length=120, null=True, verbose_name='Text facultet 1')),
                ('description_facultet1', models.TextField(verbose_name='Description facultet 1')),
                ('description_facultet1_ru', models.TextField(null=True, verbose_name='Description facultet 1')),
                ('description_facultet1_en', models.TextField(null=True, verbose_name='Description facultet 1')),
                ('description_facultet1_uz', models.TextField(null=True, verbose_name='Description facultet 1')),
                ('picture_facultet1', models.ImageField(upload_to='media/first_block/', verbose_name='Picture facultet 1')),
                ('text_facultet2', models.CharField(max_length=120, verbose_name='Text facultet 2')),
                ('text_facultet2_ru', models.CharField(max_length=120, null=True, verbose_name='Text facultet 2')),
                ('text_facultet2_en', models.CharField(max_length=120, null=True, verbose_name='Text facultet 2')),
                ('text_facultet2_uz', models.CharField(max_length=120, null=True, verbose_name='Text facultet 2')),
                ('description_facultet2', models.TextField(verbose_name='Description facultet 2')),
                ('description_facultet2_ru', models.TextField(null=True, verbose_name='Description facultet 2')),
                ('description_facultet2_en', models.TextField(null=True, verbose_name='Description facultet 2')),
                ('description_facultet2_uz', models.TextField(null=True, verbose_name='Description facultet 2')),
                ('picture_facultet2', models.ImageField(upload_to='media/first_block/', verbose_name='Picture facultet 2')),
                ('years', models.SmallIntegerField(default=20, verbose_name='Valid for Years')),
                ('text_facultet3', models.CharField(max_length=120, verbose_name='Text facultet 3')),
                ('text_facultet3_ru', models.CharField(max_length=120, null=True, verbose_name='Text facultet 3')),
                ('text_facultet3_en', models.CharField(max_length=120, null=True, verbose_name='Text facultet 3')),
                ('text_facultet3_uz', models.CharField(max_length=120, null=True, verbose_name='Text facultet 3')),
                ('description_facultet3', models.TextField(verbose_name='Description facultet 3')),
                ('description_facultet3_ru', models.TextField(null=True, verbose_name='Description facultet 3')),
                ('description_facultet3_en', models.TextField(null=True, verbose_name='Description facultet 3')),
                ('description_facultet3_uz', models.TextField(null=True, verbose_name='Description facultet 3')),
                ('picture_facultet3', models.ImageField(upload_to='media/first_block/', verbose_name='Picture facultet 3')),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/management/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=120, verbose_name='ФИО: ')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='ФИО: ')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='ФИО: ')),
                ('name_uz', models.CharField(max_length=120, null=True, verbose_name='ФИО: ')),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='ФИО')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='ФИО')),
                ('name_uz', models.CharField(max_length=120, null=True, verbose_name='ФИО')),
                ('post', models.TextField(max_length=250, verbose_name='Post')),
                ('post_ru', models.TextField(max_length=250, null=True, verbose_name='Post')),
                ('post_en', models.TextField(max_length=250, null=True, verbose_name='Post')),
                ('post_uz', models.TextField(max_length=250, null=True, verbose_name='Post')),
                ('photo', models.ImageField(upload_to='media/professors/', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='ФИО')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='ФИО')),
                ('name_uz', models.CharField(max_length=120, null=True, verbose_name='ФИО')),
                ('post', models.TextField(max_length=250, verbose_name='Post')),
                ('post_ru', models.TextField(max_length=250, null=True, verbose_name='Post')),
                ('post_en', models.TextField(max_length=250, null=True, verbose_name='Post')),
                ('post_uz', models.TextField(max_length=250, null=True, verbose_name='Post')),
                ('photo', models.ImageField(upload_to='media/students', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Name of')),
                ('title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('title_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('title_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managements_awards', to='main.management')),
                ('professors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors_awards', to='main.professors')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_awards', to='main.students')),
            ],
        ),
    ]
