# Generated by Django 3.2.6 on 2021-08-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Name of')),
                ('title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('title_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('title_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='main.management')),
            ],
        ),
        migrations.CreateModel(
            name='AwardsProfessors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Name of')),
                ('title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('title_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('title_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('professors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='main.professors')),
            ],
        ),
        migrations.CreateModel(
            name='AwardsStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Name of')),
                ('title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('title_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('title_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name of')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='main.students')),
            ],
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
    ]
