# Generated by Django 3.2.6 on 2021-08-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_science'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='science',
            name='image',
        ),
        migrations.AddField(
            model_name='science',
            name='image1',
            field=models.ImageField(default='hello', upload_to='media/science', verbose_name='Image 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='science',
            name='image2',
            field=models.ImageField(default='hello', upload_to='media/science', verbose_name='Image 2'),
            preserve_default=False,
        ),
    ]
