# Generated by Django 3.2.6 on 2021-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210825_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.CharField(default='Conference', max_length=120, verbose_name='Name')),
                ('image1', models.ImageField(upload_to='media/conference', verbose_name='Image 1')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('text1_ru', models.TextField(null=True, verbose_name='Text 1')),
                ('text1_en', models.TextField(null=True, verbose_name='Text 1')),
                ('text1_uz', models.TextField(null=True, verbose_name='Text 1')),
                ('image2', models.ImageField(upload_to='media/conference', verbose_name='Image 2')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('text2_ru', models.TextField(null=True, verbose_name='Text 2')),
                ('text2_en', models.TextField(null=True, verbose_name='Text 2')),
                ('text2_uz', models.TextField(null=True, verbose_name='Text 2')),
                ('image3', models.ImageField(upload_to='media/conference', verbose_name='Image 3')),
                ('text3', models.TextField(verbose_name='Text 3')),
                ('text3_ru', models.TextField(null=True, verbose_name='Text 3')),
                ('text3_en', models.TextField(null=True, verbose_name='Text 3')),
                ('text3_uz', models.TextField(null=True, verbose_name='Text 3')),
            ],
        ),
    ]
