# Generated by Django 3.2.6 on 2021-08-25 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image10',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/gallery/', verbose_name='Image 10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='image11',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/gallery/', verbose_name='Image 11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='image9',
            field=models.ImageField(default='ehlksdf', upload_to='media/gallery/', verbose_name='Image 9'),
            preserve_default=False,
        ),
    ]
