# Generated by Django 3.2.6 on 2021-08-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210825_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Answers')),
                ('question', models.CharField(max_length=250, verbose_name='Question')),
                ('question_ru', models.CharField(max_length=250, null=True, verbose_name='Question')),
                ('question_en', models.CharField(max_length=250, null=True, verbose_name='Question')),
                ('question_uz', models.CharField(max_length=250, null=True, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_ru', models.TextField(null=True, verbose_name='Answer')),
                ('answer_en', models.TextField(null=True, verbose_name='Answer')),
                ('answer_uz', models.TextField(null=True, verbose_name='Answer')),
            ],
        ),
    ]
